### ISSUE TITLE
site doesn't seem to update after new release of a plugin

### ISSUE THREAD

**Issue by Manticore-007** [saadbruno/openrct2_plugin_repository#24] opened 2022-09-07 10:37 UTC

**Comment by saadbruno** [comment] 2022-09-11 15:44
duplicate of #23 

I manually updated all plugins for now

**Closed by saadbruno** 2022-09-11 15:44 UTC

**Comment by saadbruno** [comment] 2022-09-12 01:28
Just a quick update. #23 should be fixed now! Lemme know if the issue persists!

**Comment by Manticore-007** [comment] 2022-09-12 05:18
Will do, thank you!

**Comment by Manticore-007** [comment] 2023-01-31 08:58
> Just a quick update. #23 should be fixed now! Lemme know if the issue persists!

Hello Bruno, the site updates as it should, but the recently updated isn't updated and the update icon also doesn't update. Just wamted to let you know. I really love the site!

![Screenshot_20230131_095638_Chrome.jpg](https://user-images.githubusercontent.com/71702374/215714573-b64747fc-6ecb-46b1-9c21-43ad7447c90a.jpg)

![Screenshot_20230131_095623_Chrome.jpg](https://user-images.githubusercontent.com/71702374/215714605-4ab98f18-6883-4f02-9457-5b5fb211b394.jpg)

**Comment by saadbruno** [comment] 2023-01-31 09:32
I'll take a look this week. Thanks for letting me know!

**Comment by saadbruno** [comment] 2023-02-08 17:04
@Manticore-007 I found the bug and fixed it!
Thanks a bunch for letting me know about the issue, and lemme know if it persists in the future

![image](https://user-images.githubusercontent.com/23201434/217600665-3ad26019-9a4e-4cf9-954b-8b415bcf6c12.png)

**Comment by Manticore-007** [comment] 2023-02-08 17:16
It was my pleasure. I love the site, it looks nice and is very convenient. Thanks for fixing the issue!
